name: bluetooth_manager
description: A simple plugin to manage Bluetooth, turning on and off ang geting Bluetooth state.
version: 0.0.11
homepage: https://github.com/FabioClem/bluetooth_manager

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fahen.bluetooth_manager
        pluginClass: BluetoothManagerPlugin